---
all:
  children:
    gui_vms:
      hosts:
        gui-automation-staging:
          ansible_host: "{{ lookup('env', 'STAGING_HOST') | default('192.168.56.104', true) }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('admin', true) }}"
          ansible_become: true
