---
all:
  children:
    gui_vms:
      hosts:
        gui-automation-prod:
          ansible_host: "{{ lookup('env', 'GUI_VM_HOST') | default('192.168.56.103', true) }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('admin', true) }}"
          ansible_become: true
